### PR TITLE
fixes: ImageStyle dependency not injected properly

### PR DESCRIPTION
**Pull request by D4KO**

### CODE REVIEW

**Comment by D4KO** [comment]
Merged. Well done! I confirm I've accepted your invitation :)

**Comment by D4KO** [comment]
Pass it through the coding standards validator and send me results pls. I'm
curious...

**Comment by D4KO** [comment]
Btw. If you're still interested in GIT, this link might be useful
https://www.atlassian.com/git/tutorials/comparing-workflows/forking-workflow
Yeah, it's written for Bitbucket. The principals are the same.
Today we've successfully collaborate by the help of Fork Flow. The most fav
flow on open-source projects.

**Comment by D4KO** [comment]
No patches. No applying. Develop separately in your own fork and merge
optionaly to others only what's needed.

**Comment by D4KO** [comment]
This is the way we'll be collaborating on the code together in next steps.
Spinning this wheel.
You commits pushes to your 'official' fork.
I fetch you changes from your repo to mine and develop separately.
Finally I'll push my repo master to yours and trigger the pull request via
UI.
You check my changes. Make a comment if something looks curious. If not,
merge my pull request changes in UI into your public repo.
That's all. git pull on your local machine to fetch changes from your
freshly updated public repo master

**Comment by D4KO** [comment]
git pull should sync your local repo with the public one without any
conflicts.
hmm, you know shit happens...

**Review by fkelly12054 — COMMENTED** [review]
x

**Pull request merged**
